# $Id$

CC = gcc

CDEBUGFLAGS = -O

CDEFS = -I/usr/openwin/include  -Dsun -Dsparc -DBSD \
	-D_XFUNCPROTOBEGIN="" -D_XFUNCPROTOEND=""

CFLAGS = $(CDEBUGFLAGS) $(CDEFS)

LIBS = -L/usr/openwin/lib -lXaw -lXmu -lXt -lXext -lX11

SRCS = gridboxdemo.c Gridbox.c
OBJS = $(SRCS:.c=.o)

all: gridboxdemo

gridboxdemo: $(OBJS)
	$(CC) -o $@ $(OBJS) $(LIBS)

clean:
	rm -f gridboxdemo
	rm -f *.CKP *.BAK *.bak *.o core errs tags TAGS
